admin/protected/models/Users.php
<?php

/**
 * This is the model class for table "users".
 *
 * The followings are the available columns in table 'users':
 * @property integer $id
 * @property string $username
 * @property string $first_name
 * @property string $last_name
 * @property string $password
 * @property string $email
 * @property string $phone
 * @property string $mobile
 * @property string $image
 * @property string $user_type
 * @property integer $created_by
 * @property integer $status
 * @property string $date_added
 * @property string $date_modified
 */
class Users extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'users';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('username, first_name, last_name, password, email, user_type, created_by, date_added, date_modified', 'required'),
			array('created_by', 'numerical', 'integerOnly'=>true),
			array('username, first_name, last_name, email, status', 'length', 'max'=>256),
			array('user_type', 'length', 'max'=>20),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, username, first_name, last_name, password, email, image, user_type, created_by, status, date_added, date_modified', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'username' => 'Username',
			'first_name' => 'First Name',
			'last_name' => 'Last Name',
			'password' => 'Password',
			'email' => 'Email',
			'image' => 'Image',
			'user_type' => 'User Type',
			'created_by' => 'Created By',
			'status' => 'Status',
			'date_added' => 'Date Added',
			'date_modified' => 'Date Modified',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('username',$this->username,true);
		$criteria->compare('first_name',$this->first_name,true);
		$criteria->compare('last_name',$this->last_name,true);
		$criteria->compare('password',$this->password,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('image',$this->image,true);
		//$criteria->compare('user_type','employee');
		$criteria->compare('created_by',$this->created_by);
		$criteria->compare('status',$this->status);
		$criteria->compare('date_added',$this->date_added,true);
		$criteria->compare('date_modified',$this->date_modified,true);
		$criteria->addCondition('user_type != "admin" ');

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	// public function addemployee()
	// {
		//@todo Please modify the following code to remove attributes that should not be searched.

		// $criteria=new CDbCriteria;

		// $criteria->compare('id',$this->id);
		// $criteria->compare('username',$this->username,true);
		// $criteria->compare('first_name',$this->first_name,true);
		// $criteria->compare('last_name',$this->last_name,true);
		// $criteria->compare('password',$this->password,true);
		// $criteria->compare('email',$this->email,true);
		// $criteria->compare('image',$this->image,true);
		// $criteria->compare('user_type','employee');
		// $criteria->compare('created_by',$this->created_by);
		// $criteria->compare('status',$this->status);
		// $criteria->compare('date_added',$this->date_added,true);
		// $criteria->compare('date_modified',$this->date_modified,true);

		// return new CActiveDataProvider($this, array(
			// 'criteria'=>$criteria,
		// ));
	// }

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Users the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

admin/protected/controllers/UsersController.php
<?php

class UsersController extends Controller
{
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','DeactivateUser','ActivateUser','AddEmployee','CreateEmployee','UpdateEmployee','CompanyCreate'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	public function actionCreate()
	{
		$model=new Users;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Users']))
		{
			$model->attributes=$_POST['Users'];
			$password = $this->better_crypt($model->password);
			$model->password = $password;
			$model->status = 1;
			$date_added = date('Y-m-d H:i:s');
			$model->date_added = $date_added;
			$model->date_modified = $date_added;
			$model->created_by = Yii::app()->user->id;
			$model->admin_id = (Yii::app()->user->id ? Yii::app()->user->id : 0 );

			$image = CUploadedFile::getInstance($model,'image');
			if($image !== null) {
				$image_new_name = time().$image->name;
			}
			else {
					$image_new_name =null;
			}
			$model->image = $image_new_name;

			if($model->save()){

				$path = Yii::app()->basePath.'/../images/users';
				if($image !== null) {
				$image->saveAs($path.'/'.$image_new_name);
	
				Yii::app()->user->setFlash('success',
						"<strong>
						<i class='icon-ok'></i>
						Users has been created successfully!	
					   </strong>");
					
				$model=new Users;
			}
		}
	}
	$this->render('create',array(
			'model'=>$model,
		));
}

	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$prevImage=$model->image;

		if(isset($_POST['Users']))
		{
			$model->attributes=$_POST['Users'];

			$imageUser=CUploadedFile::getInstance($model,'image');
			
			if($imageUser !== null) {
				$image_name= time().$imageUser->name;
				$model->image = $image_name;
				$path = Yii::app()->basePath.'/../images/users/' .$model->image;
				$imageUser->saveAs($path);
			}else{
				$model->image=$prevImage;
			}

			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}
	
	public function actionCreateEmployee()
	{
		$model=new Users;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Users']))
		{
			$model->attributes=$_POST['Users'];
			$password = $this->better_crypt($model->password);
			$model->password = $password;
			$model->status = 1;
			$date_added = date('Y-m-d H:i:s');
			$model->date_added = $date_added;
			$model->date_modified = $date_added;
			$model->created_by = Yii::app()->user->id;
		    $model->user_type = 'employee';

			$image = CUploadedFile::getInstance($model,'image');
			if($image !== null) {
				$image_new_name = time().$image->name;
			}
			else {
					$image_new_name =null;
			}
			$model->image = $image_new_name;

			if($model->save()){

				$path = Yii::app()->basePath.'/../images/employee';
				if($image !== null) {
				$image->saveAs($path.'/'.$image_new_name);
	
				Yii::app()->user->setFlash('success',
						"<strong>
						<i class='icon-ok'></i>
						Employee has been created successfully!
						
					   </strong>");
					   $this->redirect(array('view','id'=>$model->id));
				$model=new Users;
			}
		}
	}
	$this->render('createemployee',array(
			'model'=>$model,
		));
}


public function actionUpdateEmployee($id)
	{
		$model=$this->loadModel($id);
		$prevImage=$model->image;

		if(isset($_POST['Users']))
		{
			$model->attributes=$_POST['Users'];

			$imageUser=CUploadedFile::getInstance($model,'image');
			
			if($imageUser !== null) {
				$image_name= time().$imageUser->name;
				$model->image = $image_name;
				$path = Yii::app()->basePath.'/../images/employee/' .$model->image;
				$imageUser->saveAs($path);
			}else{
				$model->image=$prevImage;
			}

			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('updateemployee',array(
			'model'=>$model,
		));
	}

	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Users');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	public function actionAdmin()
	{
		$model=new Users('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Users']))
			$model->attributes=$_GET['Users'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	
	
		public function actionAddEmployee()
	{
		$model=new Users('addemployee');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Users']))
			$model->attributes=$_GET['Users'];

		$this->render('addemployee',array(
			'model'=>$model,
		));
	}

	public function loadModel($id)
	{
		$model=Users::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='users-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	private function better_crypt($input, $rounds = 7)
	{
    $salt = "";
    $salt_chars = array_merge(range('A','Z'), range('a','z'), range(0,9));
    for($i=0; $i < 22; $i++) {
      $salt .= $salt_chars[array_rand($salt_chars)];
    }
	
    return crypt($input, sprintf('$2a$%02d$', $rounds) . $salt);
  }


	public function actionDeactivateUser(){
		$id = $_POST['id'];

		$Users = Users::model()->updateAll(array('status'=>'2'),"id = $id");

		if($Users){
			echo "success";
		}
		else{
			"fail";
		}
	}
	
	public function actionActivateUser(){
		$id = $_POST['id'];

		$Users = Users::model()->updateAll(array('status'=>'1'),"id = $id");

		if($Users){
			echo "success";
		}
		else{
			"fail";
		}
	}

}

admin/protected/views/users/_form.php
<div class="row">
   <div class="col-md-12 col-xs-12">
      <div class="x_panel">
         <div class="x_title">
             <h1>Create Users</h1>
                <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'users-form',
	'enableAjaxValidation'=>true,
	'htmlOptions' => array('enctype' => 'multipart/form-data'),
)); ?>
<?php echo $form->errorSummary($model); ?>
					
					<div class="col-md-8 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
          <?php echo $form->labelEx($model,'username'); ?>
					<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>256,'class'=>'form-control')); ?>
					<?php echo $form->error($model,'username'); ?>
          </div>


          <div class="col-md-8 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
          <?php echo $form->labelEx($model,'first_name'); ?>
          <?php echo $form->textField($model,'first_name',array('size'=>60,'maxlength'=>256,'class'=>'form-control')); ?>
					<?php echo $form->error($model,'first_name'); ?>
          </div>

          <div class="col-md-8 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
          <?php echo $form->labelEx($model,'last_name'); ?>
          <?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>256,'class'=>'form-control')); ?>
					<?php echo $form->error($model,'last_name'); ?>
          </div>

          <div class="col-md-8 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
          <?php echo $form->labelEx($model,'email'); ?>
          <?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>256,'class'=>'form-control')); ?>
					<?php echo $form->error($model,'email'); ?>
          </div>

          <div class="col-md-8 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
          <?php echo $form->labelEx($model,'password'); ?>
          <?php 
							if($model->isNewRecord){
								$attributes = array('size'=>60,'maxlength'=>256,'class'=>'form-control'); 
							}else{
								$attributes = array('size'=>60,'maxlength'=>256,'class'=>'form-control','disabled'=>'disabled','value'=>'***************','readonly'=>'readonly'); 
							}
						?>
		        <?php echo $form->passwordField($model,'password', $attributes); ?>
            </div>

          <div class="col-md-8 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
          <?php echo $form->labelEx($model,'user_type'); ?>
          <?php $temp_list =  array('superadmin'=>'Super Admin', 'admin'=>'Admin', 'manager'=>'Manager', 'operator'=>'Computer Operator', 'waiter'=>'Waiter'); ?>
          <?php echo $form->dropDownList($model,'user_type', $temp_list, array('value'=>$model->user_type,'empty'=>'Please Select','class'=>'form-control')); ?>
          <?php echo $form->error($model,'user_type'); ?>
          </div> 

            <div class="col-md-8 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
            <?php echo $form->labelEx($model,'image'); ?>
						<?php echo $form->fileField($model,'image',array('rows'=>3, 'cols'=>30,'class'=>'form-control')); ?>
						<?php echo $form->error($model,'image'); ?>
            </div>

                      <div class="form-group" style="margin-top: 1%">
                        <div class="col-md-8 col-sm-9 col-xs-12">
                          <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class'=>'btn btn-success')); ?>
                        </div>
                      </div>

                    <?php $this->endWidget(); ?>
                  </div>
                </div>
               </div>
              </div>

admin/protected/views/users/_search.php
<div class="row">
<div class="col-md-12 col-xs-12">
<div class="x_title">
       <h1>Manage Employee Information</h1>
<ul class="nav navbar-right panel_toolbox">
	<a href="<?php echo Yii::app()->createUrl('users/create'); ?>" class="btn btn-danger" style="float:right">
	<i class="fa fa-plus"></i> Add Employee</a>
</ul>

<div class="clearfix"></div>
</div>
                  
<div class="x_content">
<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>
					
					<div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback" style="margin-top: 1%">
          <?php echo $form->labelEx($model,'username'); ?>
					<?php echo $form->textField($model,'username',array('size'=>60,'maxlength'=>256,'class'=>'form-control')); ?>
                     </div>


                      <div class="col-md-6 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
                      <?php echo $form->labelEx($model,'first_name'); ?>
                        <?php echo $form->textField($model,'first_name',array('size'=>60,'maxlength'=>256,'class'=>'form-control')); ?>
                      </div>

                       <div class="col-md-6 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
                       <?php echo $form->labelEx($model,'last_name'); ?>
                        <?php echo $form->textField($model,'last_name',array('size'=>60,'maxlength'=>256,'class'=>'form-control')); ?>
                      </div>

                      <div class="col-md-6 col-sm-6 col-xs-12 form-group" style="margin-top: 1%">
                      <?php echo $form->labelEx($model,'last_name'); ?>
                        <?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>256,'class'=>'form-control')); ?>
                      </div>

                      <div class="form-group">
                        <div class="col-md-8 col-sm-9 col-xs-12">
                          <?php echo CHtml::submitButton('Search',array('class'=>'btn btn-success')); ?>
                        </div>
                      </div>

<?php $this->endWidget(); ?>
</div>

</div>
</div>

admin/protected/views/users/_view.php
<?php
/* @var $this UsersController */
/* @var $data Users */
?>

<tr>

  <td>
  <a href="<?php echo Yii::app()->CreateUrl('Users/View/'.$data->id)?>">
	<img src="<?php echo Yii::app()->baseUrl .'/images/users/'.$data->image; ?>" onerror="this.src='<?php echo Yii::app()->baseUrl; ?>/images/not_found.png'" alt="" width="50" height="50" />
	</a>
     </td>
	
    <td>
	<?php echo CHtml::encode($data->username); ?>
    </td>
	
	 <td>
		<?php echo CHtml::encode($data->first_name); ?>
    </td>
	 
	 <td>
		<?php echo CHtml::encode($data->last_name); ?>
     </td>
	 
	 <td>
		<?php echo CHtml::encode($data->email); ?>
     </td>

     <td>
		<?php echo CHtml::encode($data->user_type); ?>
     </td>
	 
    <td>
	  <?php if($data->status == 1){ ?>
        <p style="color: #27883d; font-weight: 600" class="active_user">Active</p>
      <?php } else { ?>
      	<p style="color: #b61007; font-weight: 600" class="deactive_user">Deactive</p>
      <?php } ?>
     </td>
 

	 <td>
		<a href="<?php echo Yii::app()->CreateUrl('Users/Update/'.$data->id)?>" class="fa fa-pencil btn btn-primary"></a>
		<a href="<?php echo Yii::app()->CreateUrl('Users/View/'.$data->id)?>" class="fa fa-eye btn btn-info"></a>

		<!-- <a href="<?php echo Yii::app()->CreateUrl('Users/DeleteRow/'.$data->id)?>" class="fa fa-trash-o btn btn-danger"></a> -->
		
		<?php if($data->status == 1){ ?>
		<a href="javascript:void(0)" data-id='<?php echo $data->id; ?>' class="fa fa-ban btn btn-danger ban" data-toggle="tooltip" data-placement="top" title="Deactivate"></a>
		<?php } else { ?>
		<a href="javascript:void(0)" data-id='<?php echo $data->id; ?>' class="fa fa-check btn btn-success active" data-toggle="tooltip" data-placement="top" title="Active"></a>
		<?php } ?>
	</td>
  </tr>

admin/protected/views/users/admin.php
<?php
/* @var $this UsersController */
/* @var $model Users */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Manage',
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#users-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<div class="search-form">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->


<br>


<div class="container">
<div class="row">
<div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Employee Information</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  <div class="table-responsive">
                    <table id="datatable" class="table table-striped table-bordered table-hover">
                      <thead>
                        <tr>

                        <th scope="col" style="width: 50px !important;">
							Image
						</th>
									
						<th scope="col" style="width: 80px !important;">
							Username
						</th>
									
						<th scope="col" style="width: 120px !important;">
							Name
						</th>
									
						<th scope="col" style="width: 120px !important;">
							Last Name
						</th>
									
						<th scope="col" style="width: 120px !important;">
							Email
						</th>

						<th scope="col" style="width: 120px !important;">
							User type
						</th>
							
						<th scope="col" style="width: 120px !important;">
							Status
						</th>		
		

						<th scope="col" style="width: 250px !important;">
							Action
						</th>

                    </tr>
                  </thead>
                  <tbody>
                      			<?php $this->widget('zii.widgets.CListView', array(
									'dataProvider'=>$model->search(),
									'itemView'=>'_view',
								)); ?>
                  </tbody>

                    </table>
                    </div>
                  </div>
                </div>
              </div>
             </div>
           </div>


<script>
$('.search-button').click(function(){
	
	$('.search-form').toggle();
	return false;
});
</script>

<script>
$(document).ready(function(){

	$(".ban").click(function() {
	
	current_row = $(this);

	id = $(this).attr('data-id');

	var r = confirm(" Do you really want to Deactivate this User ? ");
    if (r == false) {
        return;
    }

$.ajax({ 
	  type: "POST",
	  url: "<?php echo $this->createUrl('Users/DeactivateUser'); ?>",
	  data: {id: id},
	  success: function(data){ 
	  if(data == 'success'){
		current_row.closest('tr').remove();
		alert("Deactivated Successfully");
		}
		else if(data == 'fail'){
			alert("Something went Wrong");	
		}
	},
	 error: function(xhr, status, error) {
			alert(xhr.responseText);
		} 
		});
});


$(".active").click(function() {
	
	current_row = $(this);

	id = $(this).attr('data-id');

	var r = confirm(" Do you really want to Activate this User ? ");
    if (r == false) {
        return;
    }

$.ajax({ 
	  type: "POST",
	  url: "<?php echo $this->createUrl('Users/ActivateUser'); ?>",
	  data: {id: id},
	  success: function(data){ 
	  if(data == 'success'){
	  		current_row.closest('tr').find('.deactive_user').text(" ");
			current_row.closest('tr').find('.deactive_user').append( "<p style='color: #27883d; font-weight: 600'>Active</p>" );
		}
		else if(data == 'fail'){
			alert("Something went Wrong");	
		}
	},
	 error: function(xhr, status, error) {
			alert(xhr.responseText);
		} 
		});
});

});
</script>

admin/protected/views/users/create.php
<?php
/* @var $this UsersController */
/* @var $model Users */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	'Create',
);

?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

admin/protected/views/users/index.php
<?php
/* @var $this UsersController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Users',
);

$this->menu=array(
	array('label'=>'Create Users', 'url'=>array('create')),
	array('label'=>'Manage Users', 'url'=>array('admin')),
);
?>

<h1>Users</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

admin/protected/views/users/update.php
<?php
/* @var $this UsersController */
/* @var $model Users */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

admin/protected/views/users/updateemployee.php
<?php
/* @var $this UsersController */
/* @var $model Users */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

admin/protected/views/users/view.php
<?php
/* @var $this UsersController */
/* @var $model Users */

$this->breadcrumbs=array(
	'Users'=>array('index'),
	$model->id,
);

?>

<h1>View Employee</h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'username',
		'first_name',
		'last_name',
		
		'email',
		
		'image',
		'user_type',
		
		'date_added',
		'date_modified',
	),
)); ?>